### ISSUE TITLE
[Android] Continue button is getting enable before invitation is accepted on “Enter Invite code” screen. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1227]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung Galaxy S4 (5.0.1), Samsung j7 prime (6.0.1), Samsung Galaxy A8+ (8.0.0) 
**Priority:** High

**Pre-condition:**  User should have an invitation code.  
**Repro Steps:** 
1. Launch the app and choose the language. 
2. Enter Full name, select country and enter the mobile number. 
3. Set the PIN for the app. 
4. Paste the invitation code. 
5. Observe. 

**Current Behavior:**  Continue button is getting enable before invitation is accepted
**Expected Behavior:** Continue button should remain in disable state until invitation is accepted
**Attachment:** [Android_ContinueButtonEnableIssue.mp4](https://drive.google.com/file/d/1367LYddI14-hWDblKcGUuFxRRKAyKO1B/view?usp=sharing) (Bug observe after 24  sec)

**Comment by Lss-Ankit** [comment]
@jmrossy **Update on Issue:** Verified with play store build v1.5.0 and observed that "Redeem invite Timed out" error is shown after pasting the invite code but "Continue" button remain enable hence user is able to proceed for sign up in the app. 

**Investigation:**
1) Error "Failure redeeming code" is shown when the user tap on the "Paste invite code!" button for a second time. 

Attachment: [Android_RedeeminviteTimeout.mp4](https://drive.google.com/file/d/16qE6-ULSm1qXQk47cGBrVqW6fAmQO9vU/view?usp=sharing)

**Comment by jmrossy** [comment]
Thanks Ankit, good catch!
This was fixed here: https://github.com/celo-org/celo-monorepo/pull/1214

**Comment by Lss-Ankit** [comment]
@jmrossy Thanks for the quick response, Can you please let me know on which version issue was fixed as on Play store v1.5.0 is still reproduced.

**Comment by martinvol** [comment]
@Lss-Ankit it should land with the next update!

**Comment by Lss-Ankit** [comment]
@martinvol Okay, thanks for the update!

**Comment by Lss-Ankit** [comment]
Verified with Android  Zero - sync build v1.5.0 and observed that the issue is fixed.
