### ISSUE TITLE
[Android] App get crashed when user taps on “Send an issue report” option from the “Setting” screen.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1437]
**Frequency:** 100%
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro on:** Samsung Galaxy Grand Prime (5.1.1), Samsung Galaxy s5 (6.0.1) 
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the “Cog” icon. 
3) Tap on send an issue report. 
4) Observe. 

**Impact:** User is blocked to send an issue log. 
**Current Behavior:** App gets crashed. 
**Expected Behavior:** User should be able to create an issue log
**Attachment:** 
1) [Android_AppGetCrashed.mp4](https://drive.google.com/file/d/1WPZCIvcDQX6VX_V6tw0zJfr4Dvt8uGsC/view?usp=sharing) (Bug observe at 6 sec)
2) [Crashlog.txt](https://github.com/celo-org/celo-monorepo/files/3762347/Crashlog.txt)

**Comment by jmrossy** [comment]
It seems he hit an OOM error. The logs can get big. I'll see if we can patch this in an easy way

**Comment by jmrossy** [comment]
Related: https://github.com/itinance/react-native-fs/issues/598

**Comment by jmrossy** [comment]
We may be able to switch to using https://github.com/joltup/rn-fetch-blob instead to stream the file gradually.

**Comment by Lss-Ankit** [comment]
Verified with latest Android build v1.6.1 and found that issue is fixed as now user is able to send the report using "Send an issue report" option from setting. 

I have also verify the issue on latest iOS Test flight build v1.6.1 (23) and found the following  

- Nothing happen when user taps on Send an issue Report option from setting. 

Attachment: [IOS_SendReportIssue.mp4](https://drive.google.com/file/d/151RUNg00BBF8hW9G1deAIv2U3Pg0Hyea/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit thank you for verifying but actually this is not yet fixed. However the crash will only occur on low-end phones when the logs get large.

As for iOS, we have fixed that and the fix will go out with the next app update.

**Comment by Lss-Ankit** [comment]
@jmrossy Thanks for the update. I have verified this issue in Android 5 & 6 os devices and issue is fixed now in play store build : 1.6.1 (104794404). 

Verified on Account : 3155641283/Backupkey (quiz egg lumber aisle juice impose control lens office caught turn skull rude planet merge hub cross purchase gown castle dinner steak license depart)

Verified on Devices : Samsung Galaxy S5 (6.0.1) & Samsung Galaxy Grand Prime (5.0.1)

Attachment : [Android 5 & 6_App does not get crashed](https://drive.google.com/file/d/1Eq3ovkDvR-c92K35ckL6ERj0MzKZn_bJ/view?usp=sharing)
