### ISSUE TITLE
“Requested $ # form Contact number” section is not shown when user send the payment request first time if user doesn’t have any in-app notification section on “Wallet” tab.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2244]
**Frequency:** 100%
**App version:** Staging build v1.5.2 (104694505)
**Repro on:** Samsung Galaxy A8+(8.0.0), Samsung Galaxy Note 5 (7.0)
**Testing Account:** 518 468 2551/[Backup key. ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition**: Make sure user does not have any in-app notification section. 

**Repro Steps:** 
1) Launch the app. 
2) Tap on + tab. 
3) Select any contact user. 
4) Enter an amount and tap on the “Request” button. 
5) Tap on the “Request” button from the Request Payment screen.
6) Observe Requested $ # from contact number” section is not shown.  

**Impact:** * Payment request section is not shown even when user has proceeded for the payment request. 
**Investigation:** Issue does not repro if any in-app notification is exist.
**Current Behavior:** Payment request section is not shown
**Expected Behavior:** Payment request section Should show even if user does not have any in-app notification section. 
**Attachment:** [Android_PaymentRequestedFromIsnotShown.mp4](https://drive.google.com/file/d/1g0b73sOKdf26VKIT3kBlbe6eddWEXpIH/view?usp=sharing) (Bug observed at 13 sec)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS Test Flight build v1.5.2 (16) and found the issue is also reproduced in IOS.

- "Payment You've Requested" section is not shown when user sends the payment request if the user doesn’t have any in-app notification section on the “Wallet” tab.

**Attachment:** [IOS_PaymentYou've_SectionnotShown.mov](https://drive.google.com/file/d/1bc5xZkQLw5GpGiigMLYcKHOoLk1838jW/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS test flight build v 1.5.2 (17) and found that the issue is still reproduced. 

- "Payment You've Requested" section is not shown when the user sends the payment request if the user doesn’t have any in-app notification section on the “Wallet” tab.

Attachment: [IOS_PaymentRequestSectionNOtShown.mp4](https://drive.google.com/file/d/1SuXTOfELjs-DeoT7AbbiIt6WlJr2bYyP/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with IOS test flight build v1.5.2 (18) and found that the issue is fixed. 

- “Requested $ # form Contact number” section is shown when user send the payment request first time even if user doesn’t have any in-app notification section on “Wallet” tab.

Attachment: [IOS_Fixed_PaymentRequested.mp4](https://drive.google.com/file/d/1TogdjQk4Z3AllL8gGFMlTgeeU4llv8oe/view?usp=sharing)

**Note:** Will close this ticket once the issue is get fixed for Android.

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android v1.5.2 (101548777) integration build and observed that issue is still reproduced: 
- “Requested $ # form Contact number” section is not shown when user send the payment request first time if user doesn’t have any in-app notification section on “Wallet” tab.

Attachment: [Android_PaymentRequestSection.mov](https://drive.google.com/file/d/1uWYH5joS-hPDOODxLVmtYYDbmjcYBLKN/view?usp=sharing)

**Comment by jmrossy** [comment]
This is fixed in the latest integration builds, the problem was the DB issue that @jeanregisser fixed!
@Lss-Ankit I will provide you with a new build to retest with next week :)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with  Android internal Celo staging v1.5.2 (104794304) and found that issue is still reproduced. 

- “Requested $ # form Contact number” section is not shown when user send the payment request first time if user doesn’t have any in-app notification section on “Wallet” tab.

Attachment: [Android_PaymentrequestSectionNotShown.mp4 ](https://drive.google.com/file/d/1cdJ3EgiRJWhqtm5VsqqRI6jnFOvxhOl1/view?usp=sharing) (Bug observe after 12 sec)

**Comment by Lss-Ankit** [comment]
Verified with Android play store build v1.6.1 and found that issue is fixed. 

- “Requested $ # form Contact number” section is shown when user send the payment request first time if user doesn’t have any in-app notification section on “Wallet” tab.
