### ISSUE TITLE
User is not able to edit an amount which are before decimal point value if user has entered 2 decimal value in Amount field while proceed for payment.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2247]
**Frequency:** 100%
**App version:** Staging build v1.5.2 (104694505)
**Repro on:** Samsung Galaxy A8+(8.0.0), Samsung Galaxy Note 5 (7.0)

**Repro Steps:** 
1) Launch the app. 
2) Tap on “+” tab.
3) Select any Celo contact user. 
4) Enter a two decimal value with two amounts. for example 12.34. 
5) Move to cursor to after 1 
6) Tried to enter value and observed. 

**Impact:** User is blocked to edit an amount. 
**Investigation:** Issue does not repro if user has entered only 1 decimal value. 
**Current Behavior:** User is not able to edit an amount 
**Expected Behavior:** User should be able to edit an amount. 
**Attachment:** [Android_DecimalValue.mp4 ](https://drive.google.com/file/d/1jvuVhqf70WBfZZ-WrUyuwi9idxE8Johw/view?usp=sharing)(Bug observed at 14 sec)

**Comment by annakaz** [comment]
Fixed by redesign

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is Repro 
- User is not able to edit an amount which are before decimal point value if user has entered 2 decimal value in Amount field while proceed for payment.
- **Device Used:** iPhone 6(12.4.7)
- **Attachment:** [NotableEditAmountIssue.MP4](https://drive.google.com/file/d/1G4fty1nxWZ3dCk4z2XtY9BAyWMdnauYo/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@gnardini this may be related to the other digit issues I've assigned to you

**Comment by gnardini** [comment]
This looks intended to me, it's not a normal input, so not sure if there's anything to do here.

**Comment by aleksey-nov** [comment]
closed because fixed in the new design

**Comment by Lss-Ankit** [comment]
Hi @aleksey-nov We have verified issue using  latest Android Internal Build V1.9.1(1004294332) & Test Flight Build V1.9.1(42) and found that issue is still repro as per the below observations. 

- User is not able to edit an amount which are before decimal point value if user has entered 2 decimal value in Amount field while proceed for payment.

Cam you please let us know is it expected behavior?

**Comment by Celoqa** [comment]
Hey @aleksey-nov I have verified this issue using latest Android internal build V1.15.1 & Test Flight build V1.15.1 & observed that user still not able to edit amount which is before decimal points by entering 2 decimal value. Can you please let us know is it expected behavior ?
**Verified On Devices:** Samsung Galaxy J5 Prime 8.0.0), Samsung Galaxy A5 (7.0), iPhone SE (14.2)
Thanks..!!
