### ISSUE TITLE
“No Contact Found” text is shown for while on “Contact Screen” when user open contact screen after cold the launch the app.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4093]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)
**Tested Account:** 503 447 5958 / Backup Key

Pre-condition: Application is launch after cold launch the app. 

**Repro Steps:** 
1) Launch app and login with tested account 
2) Tap on Hamburger menu. 
3) Tap on Invite option. 
4) Observe.  

**Current Behavior:**  “No contact found” screen is shown for while 
**Expected Behavior:** “Fecting contact” should be display if contact are syncing in device
**Attachment:** [ContactIssue .mp4 ](https://drive.google.com/file/d/1AxwbmTv-9Val9P3jLc7Cuwa7YKjU4y8i/view?usp=sharing)(Bug observed at 25 sec)

**Comment by tarikbellamine** [comment]
Fixed by @jmrossy

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine i have verified issue on latest test flight celo integration wallet build v1.8.2 (40) and found that issue is still reproduced. 

- “No Contact Found” text is shown for while on “Contact Screen” when user open contact screen after cold the launch the app. 

Verified On: Iphone 6+ (12.4.5) 

Please find the attachment for the same: 
Attachment: [ContactIssue.mp4](https://drive.google.com/file/d/1eHO3QDLKx97EQTdDzcfe2NOQIXnAJShX/view?usp=sharing)

**Comment by tarikbellamine** [comment]
The invite option will be removed in the next build. Can you reproduce this issue through Send or Request? If not, please close it.

**Comment by Lss-Ankit** [comment]
HI @tarikbellamine thanks for the updates!. 
I have verified the issue agian on send and request screen and found that issue is still reproduced. 

Attachment: [ContactSend&RequestIssue.mp4](https://drive.google.com/file/d/1je3IejO_4EVbIR2XpC8dWjVIA8VngMMI/view?usp=sharing)

**Comment by jmrossy** [comment]
@tarikbellamine @coreycelo Looks like we need a loading state for the Send screen while the app is still importing contacts

**Comment by coreycelo** [comment]
Updated the issue with a design to display a spinner.
