### ISSUE TITLE
The app crashes when the user warm launch app after shaking the device.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6316]
**Frequency:** 100%
**Repro on build version:** V1.6.0
**Repro on devices:** Samsung Galaxy S4(4.4.2)
**Does not repro devices** Samsung Galaxy A5(7.0)
**Testing Account:  / Backup Key:** 
515 444 0200
library huge cram diet document mimic pink trade invest arm catalog feature ocean muscle either try include canoe awful just brief proof idea figure
**Pre-condition:** User should run the application in the background.
**Repro Steps:**
1. Launch the application & login with a test account.
2. Now the user should be on the Home screen. 
3. Keep the app run in the background.
4. Now shake the device & warm launch the application.
5. Observed that,
**Current Behavior:**  The app crashes when the user warm launch the application.
**Expected Behavior:**  App should not crash & the contact screen should be displayed when the user warm launches the application.
**Impact:**  User not able to add logs by shaking device.
**Attachment:**  [CrashWhenUserShakeDevice.mp4](https://drive.google.com/file/d/1yLaxyYAVGmUlWYsdFC560ervBTrAaQcC/view?usp=sharing) [issue observed at 0.22 sec]

**Comment by jeanregisser** [comment]
Thanks @Lss-Ankit, could you recheck with v1.7?
This should be fixed by https://github.com/celo-org/celo-monorepo/pull/6230

**Comment by Lss-Ankit** [comment]
Hey @jeanregisser I have verified this issue on latest Android internal build V1.7.2(1004294329) & observe that issue is still reproduced.
**Repro on device:** Samsung Galaxy S4(4.4.2)
**Crash logs:** [celo_logs.txt](https://drive.google.com/file/d/13q67fJD9gUG3QkXM6LCuGMFN8XO69Wxl/view?usp=sharing)
**Does not repro devices:** Samsung Galaxy A5(7.0)

**Comment by jeanregisser** [comment]
Thanks Ankit, I'm decreasing the priority of this issue given it seems specific to Android 4 devices.

**Comment by ValoraQA** [comment]
Hey @jeanregisser I have verified this issue using latest Android Internal Build V 1.11.1(1004294338) & observed following.
**Observations:**

- According to design change we are not able to see Contact screen when user warm launch the application after shaking device. So closing this ticket.
- FYI: We have different issue #4684  for crash after normal warm launch.
**Verified on Devices:** Samsung Galaxy S4(4.4.2), Samsung Galaxy A5(7.0)
